services:
  postgres:
    image: postgres:17
    container_name: radarbook-postgres

    environment:
      POSTGRES_DB: radarbook
      POSTGRES_USER: radarbook
      POSTGRES_PASSWORD: radarbook_dev

    ports:
      - "5433:5432"

    volumes:
      - radarbook_postgres_data:/var/lib/postgresql/data

volumes:
  radarbook_postgres_data: