# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


# ===============================
# LOGGING
# ===============================

logging.level.root=INFO
logging.level.io.github.bolivaar16.radarbook=INFO


# ===============================
# RADARBOOK - SCRAPING
# ===============================

radarbook.scraping.connect-timeout=5s
radarbook.scraping.read-timeout=10s 