# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/radarbook}
spring.datasource.username=${DB_USERNAME:radarbook}
spring.datasource.password=${DB_PASSWORD:radarbook}


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# LOGGING
# ===============================

logging.level.root=INFO
logging.level.io.github.bolivaar16.radarbook=DEBUG


# ===============================
# RADARBOOK - SCRAPING
# ===============================

radarbook.scraping.connect-timeout=5s
radarbook.scraping.read-timeout=10s

radarbook.scrapers.sanpablo.enabled=true
radarbook.scrapers.sanpablo.base-url=https://www.sanpablo.es